// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elfnfpmzrtolhbthjawi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsZm5mcG16cnRvbGhidGhqYXdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3OTc1NTMsImV4cCI6MjA3MjM3MzU1M30.3f6DgRkGOZNL-6lxURtU6zvVXwkevE82j6qn9AGWCPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});